APP_NAME = "数智家校放学系统"
APP_VERSION = "2.0.2"
APP_VERSION_LABEL = f"版本 v{APP_VERSION}"

WINDOWS_EXE_NAME = f"{APP_NAME}.exe"
WINDOWS_ZIP_NAME = f"{APP_NAME}-v{APP_VERSION}-windows-x64.zip"
WINDOWS_SHA256_NAME = f"{WINDOWS_ZIP_NAME}.sha256"
