plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.xxt.dismissal.poc'
    compileSdk 35
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'cn.xxt.dismissal.poc'
        minSdk 28
        targetSdk 28
        versionCode 5
        versionName '0.4.0'
        def testPlatformUrl = System.getenv('TEST_PLATFORM_URL') ?: 'http://192.168.1.107:8765'
        buildConfigField 'String', 'TEST_PLATFORM_URL', '"' + testPlatformUrl + '"'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'java.awt4a-0.1-release', ext: 'aar')
}
