plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.xxt.dismissal.poc'
    compileSdk 35
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'cn.xxt.dismissal.poc'
        minSdk 28
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation(name: 'java.awt4a-0.1-release', ext: 'aar')
}
